import type { Student, University, Event } from "./types"

export const mockStudents: Student[] = [
  {
    id: "1",
    email: "john.doe@email.com",
    role: "student",
    firstName: "John",
    lastName: "Doe",
    university: "University of California, Berkeley",
    graduationYear: 2022,
    degree: "Bachelor of Science",
    major: "Computer Science",
    currentPosition: "Software Engineer",
    currentCompany: "Google",
    location: "San Francisco, CA",
    bio: "Passionate software engineer with expertise in full-stack development.",
    skills: ["JavaScript", "React", "Node.js", "Python", "Machine Learning"],
    interests: ["Technology", "Startups", "AI/ML", "Open Source"],
    careerGoals: ["Tech Leadership", "Product Management", "Entrepreneurship"],
    linkedinUrl: "https://linkedin.com/in/johndoe",
    isPublic: true,
    createdAt: new Date("2023-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    email: "jane.smith@email.com",
    role: "student",
    firstName: "Jane",
    lastName: "Smith",
    university: "Stanford University",
    graduationYear: 2021,
    degree: "Master of Business Administration",
    major: "Business Administration",
    currentPosition: "Product Manager",
    currentCompany: "Meta",
    location: "Palo Alto, CA",
    bio: "Product manager focused on user experience and growth strategies.",
    skills: ["Product Management", "Data Analysis", "UX Design", "Strategy"],
    interests: ["Product Strategy", "User Experience", "Data Science"],
    careerGoals: ["VP of Product", "Startup Founder", "Venture Capital"],
    linkedinUrl: "https://linkedin.com/in/janesmith",
    isPublic: true,
    createdAt: new Date("2023-02-20"),
    updatedAt: new Date("2024-02-20"),
  },
]

export const mockUniversities: University[] = [
  {
    id: "3",
    email: "admin@berkeley.edu",
    role: "university",
    firstName: "UC Berkeley",
    lastName: "Admin",
    universityId: "CA001234",
    universityName: "University of California, Berkeley",
    state: "California",
    establishedYear: 1868,
    website: "https://berkeley.edu",
    description: "Public research university in Berkeley, California.",
    isVerified: true,
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "4",
    email: "admin@stanford.edu",
    role: "university",
    firstName: "Stanford",
    lastName: "Admin",
    universityId: "CA005678",
    universityName: "Stanford University",
    state: "California",
    establishedYear: 1885,
    website: "https://stanford.edu",
    description: "Private research university in Stanford, California.",
    isVerified: true,
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Tech Alumni Networking Night",
    description: "Join fellow tech alumni for an evening of networking and career discussions.",
    organizerId: "3",
    organizerType: "university",
    date: new Date("2024-03-15T18:00:00"),
    location: "San Francisco, CA",
    isVirtual: false,
    maxAttendees: 100,
    currentAttendees: 45,
    tags: ["Networking", "Technology", "Career"],
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    title: "Virtual Career Fair 2024",
    description: "Connect with top employers and explore new career opportunities.",
    organizerId: "4",
    organizerType: "university",
    date: new Date("2024-04-20T10:00:00"),
    location: "Virtual Event",
    isVirtual: true,
    maxAttendees: 500,
    currentAttendees: 234,
    tags: ["Career Fair", "Jobs", "Virtual"],
    createdAt: new Date("2024-02-01"),
  },
]

// Function to initialize mock data
export function initializeMockData() {
  // This would populate the mock database with initial data
  console.log("Mock data initialized for Alumni Portal")
}
